/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppRouteImport } from './routes/app'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthRedefinirSenhaRouteImport } from './routes/auth.redefinir-senha'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthEsqueciSenhaRouteImport } from './routes/auth.esqueci-senha'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthCadastroRouteImport } from './routes/auth.cadastro'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppVisitantesRouteImport } from './routes/app.visitantes'
import { Route as AppReservasRouteImport } from './routes/app.reservas'
import { Route as AppPreferenciasNotificacaoRouteImport } from './routes/app.preferencias-notificacao'
import { Route as AppOcorrenciasRouteImport } from './routes/app.ocorrencias'
import { Route as AppMoradoresRouteImport } from './routes/app.moradores'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppEncomendasRouteImport } from './routes/app.encomendas'
import { Route as AppDocumentosRouteImport } from './routes/app.documentos'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppCondominioRouteImport } from './routes/app.condominio'
import { Route as AppFinanceiroIndexRouteImport } from './routes/app.financeiro.index'
import { Route as AuthConviteTokenRouteImport } from './routes/auth.convite.$token'
import { Route as AppFinanceiroWhatsappRouteImport } from './routes/app.financeiro.whatsapp'
import { Route as AppFinanceiroPagamentosRouteImport } from './routes/app.financeiro.pagamentos'
import { Route as AppFinanceiroInadimplenciaRouteImport } from './routes/app.financeiro.inadimplencia'
import { Route as AppFinanceiroDespesasRouteImport } from './routes/app.financeiro.despesas'
import { Route as AppFinanceiroCobrancasRouteImport } from './routes/app.financeiro.cobrancas'
import { Route as AppFinanceiroCategoriasRouteImport } from './routes/app.financeiro.categorias'
import { Route as ApiPublicWaWebhookRouteImport } from './routes/api.public.wa-webhook'
import { Route as ApiPublicWaDrainRouteImport } from './routes/api/public/wa-drain'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api.public.mp-webhook'
import { Route as ApiPublicHooksLembretesCobrancaRouteImport } from './routes/api/public/hooks/lembretes-cobranca'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRedefinirSenhaRoute = AuthRedefinirSenhaRouteImport.update({
  id: '/auth/redefinir-senha',
  path: '/auth/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEsqueciSenhaRoute = AuthEsqueciSenhaRouteImport.update({
  id: '/auth/esqueci-senha',
  path: '/auth/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/auth/cadastro',
  path: '/auth/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitantesRoute = AppVisitantesRouteImport.update({
  id: '/visitantes',
  path: '/visitantes',
  getParentRoute: () => AppRoute,
} as any)
const AppReservasRoute = AppReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AppRoute,
} as any)
const AppPreferenciasNotificacaoRoute =
  AppPreferenciasNotificacaoRouteImport.update({
    id: '/preferencias-notificacao',
    path: '/preferencias-notificacao',
    getParentRoute: () => AppRoute,
  } as any)
const AppOcorrenciasRoute = AppOcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => AppRoute,
} as any)
const AppMoradoresRoute = AppMoradoresRouteImport.update({
  id: '/moradores',
  path: '/moradores',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEncomendasRoute = AppEncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCondominioRoute = AppCondominioRouteImport.update({
  id: '/condominio',
  path: '/condominio',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroIndexRoute = AppFinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AuthConviteTokenRoute = AuthConviteTokenRouteImport.update({
  id: '/auth/convite/$token',
  path: '/auth/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFinanceiroWhatsappRoute = AppFinanceiroWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroPagamentosRoute = AppFinanceiroPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroInadimplenciaRoute =
  AppFinanceiroInadimplenciaRouteImport.update({
    id: '/inadimplencia',
    path: '/inadimplencia',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppFinanceiroDespesasRoute = AppFinanceiroDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroCobrancasRoute = AppFinanceiroCobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const AppFinanceiroCategoriasRoute = AppFinanceiroCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppFinanceiroRoute,
} as any)
const ApiPublicWaWebhookRoute = ApiPublicWaWebhookRouteImport.update({
  id: '/api/public/wa-webhook',
  path: '/api/public/wa-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaDrainRoute = ApiPublicWaDrainRouteImport.update({
  id: '/api/public/wa-drain',
  path: '/api/public/wa-drain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksLembretesCobrancaRoute =
  ApiPublicHooksLembretesCobrancaRouteImport.update({
    id: '/api/public/hooks/lembretes-cobranca',
    path: '/api/public/hooks/lembretes-cobranca',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/lgpd': typeof LgpdRoute
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recursos': typeof RecursosRoute
  '/sobre': typeof SobreRoute
  '/status': typeof StatusRoute
  '/termos': typeof TermosRoute
  '/app/condominio': typeof AppCondominioRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/encomendas': typeof AppEncomendasRoute
  '/app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/app/moradores': typeof AppMoradoresRoute
  '/app/ocorrencias': typeof AppOcorrenciasRoute
  '/app/preferencias-notificacao': typeof AppPreferenciasNotificacaoRoute
  '/app/reservas': typeof AppReservasRoute
  '/app/visitantes': typeof AppVisitantesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/esqueci-senha': typeof AuthEsqueciSenhaRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/redefinir-senha': typeof AuthRedefinirSenhaRoute
  '/app/': typeof AppIndexRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/wa-drain': typeof ApiPublicWaDrainRoute
  '/api/public/wa-webhook': typeof ApiPublicWaWebhookRoute
  '/app/financeiro/categorias': typeof AppFinanceiroCategoriasRoute
  '/app/financeiro/cobrancas': typeof AppFinanceiroCobrancasRoute
  '/app/financeiro/despesas': typeof AppFinanceiroDespesasRoute
  '/app/financeiro/inadimplencia': typeof AppFinanceiroInadimplenciaRoute
  '/app/financeiro/pagamentos': typeof AppFinanceiroPagamentosRoute
  '/app/financeiro/whatsapp': typeof AppFinanceiroWhatsappRoute
  '/auth/convite/$token': typeof AuthConviteTokenRoute
  '/app/financeiro/': typeof AppFinanceiroIndexRoute
  '/api/public/hooks/lembretes-cobranca': typeof ApiPublicHooksLembretesCobrancaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/lgpd': typeof LgpdRoute
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recursos': typeof RecursosRoute
  '/sobre': typeof SobreRoute
  '/status': typeof StatusRoute
  '/termos': typeof TermosRoute
  '/app/condominio': typeof AppCondominioRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/encomendas': typeof AppEncomendasRoute
  '/app/moradores': typeof AppMoradoresRoute
  '/app/ocorrencias': typeof AppOcorrenciasRoute
  '/app/preferencias-notificacao': typeof AppPreferenciasNotificacaoRoute
  '/app/reservas': typeof AppReservasRoute
  '/app/visitantes': typeof AppVisitantesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/esqueci-senha': typeof AuthEsqueciSenhaRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/redefinir-senha': typeof AuthRedefinirSenhaRoute
  '/app': typeof AppIndexRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/wa-drain': typeof ApiPublicWaDrainRoute
  '/api/public/wa-webhook': typeof ApiPublicWaWebhookRoute
  '/app/financeiro/categorias': typeof AppFinanceiroCategoriasRoute
  '/app/financeiro/cobrancas': typeof AppFinanceiroCobrancasRoute
  '/app/financeiro/despesas': typeof AppFinanceiroDespesasRoute
  '/app/financeiro/inadimplencia': typeof AppFinanceiroInadimplenciaRoute
  '/app/financeiro/pagamentos': typeof AppFinanceiroPagamentosRoute
  '/app/financeiro/whatsapp': typeof AppFinanceiroWhatsappRoute
  '/auth/convite/$token': typeof AuthConviteTokenRoute
  '/app/financeiro': typeof AppFinanceiroIndexRoute
  '/api/public/hooks/lembretes-cobranca': typeof ApiPublicHooksLembretesCobrancaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/lgpd': typeof LgpdRoute
  '/onboarding': typeof OnboardingRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recursos': typeof RecursosRoute
  '/sobre': typeof SobreRoute
  '/status': typeof StatusRoute
  '/termos': typeof TermosRoute
  '/app/condominio': typeof AppCondominioRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/encomendas': typeof AppEncomendasRoute
  '/app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/app/moradores': typeof AppMoradoresRoute
  '/app/ocorrencias': typeof AppOcorrenciasRoute
  '/app/preferencias-notificacao': typeof AppPreferenciasNotificacaoRoute
  '/app/reservas': typeof AppReservasRoute
  '/app/visitantes': typeof AppVisitantesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/esqueci-senha': typeof AuthEsqueciSenhaRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/redefinir-senha': typeof AuthRedefinirSenhaRoute
  '/app/': typeof AppIndexRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/api/public/wa-drain': typeof ApiPublicWaDrainRoute
  '/api/public/wa-webhook': typeof ApiPublicWaWebhookRoute
  '/app/financeiro/categorias': typeof AppFinanceiroCategoriasRoute
  '/app/financeiro/cobrancas': typeof AppFinanceiroCobrancasRoute
  '/app/financeiro/despesas': typeof AppFinanceiroDespesasRoute
  '/app/financeiro/inadimplencia': typeof AppFinanceiroInadimplenciaRoute
  '/app/financeiro/pagamentos': typeof AppFinanceiroPagamentosRoute
  '/app/financeiro/whatsapp': typeof AppFinanceiroWhatsappRoute
  '/auth/convite/$token': typeof AuthConviteTokenRoute
  '/app/financeiro/': typeof AppFinanceiroIndexRoute
  '/api/public/hooks/lembretes-cobranca': typeof ApiPublicHooksLembretesCobrancaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/app'
    | '/blog'
    | '/contato'
    | '/lgpd'
    | '/onboarding'
    | '/precos'
    | '/privacidade'
    | '/recursos'
    | '/sobre'
    | '/status'
    | '/termos'
    | '/app/condominio'
    | '/app/configuracoes'
    | '/app/documentos'
    | '/app/encomendas'
    | '/app/financeiro'
    | '/app/moradores'
    | '/app/ocorrencias'
    | '/app/preferencias-notificacao'
    | '/app/reservas'
    | '/app/visitantes'
    | '/app/whatsapp'
    | '/auth/cadastro'
    | '/auth/callback'
    | '/auth/esqueci-senha'
    | '/auth/login'
    | '/auth/redefinir-senha'
    | '/app/'
    | '/api/public/mp-webhook'
    | '/api/public/wa-drain'
    | '/api/public/wa-webhook'
    | '/app/financeiro/categorias'
    | '/app/financeiro/cobrancas'
    | '/app/financeiro/despesas'
    | '/app/financeiro/inadimplencia'
    | '/app/financeiro/pagamentos'
    | '/app/financeiro/whatsapp'
    | '/auth/convite/$token'
    | '/app/financeiro/'
    | '/api/public/hooks/lembretes-cobranca'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/blog'
    | '/contato'
    | '/lgpd'
    | '/onboarding'
    | '/precos'
    | '/privacidade'
    | '/recursos'
    | '/sobre'
    | '/status'
    | '/termos'
    | '/app/condominio'
    | '/app/configuracoes'
    | '/app/documentos'
    | '/app/encomendas'
    | '/app/moradores'
    | '/app/ocorrencias'
    | '/app/preferencias-notificacao'
    | '/app/reservas'
    | '/app/visitantes'
    | '/app/whatsapp'
    | '/auth/cadastro'
    | '/auth/callback'
    | '/auth/esqueci-senha'
    | '/auth/login'
    | '/auth/redefinir-senha'
    | '/app'
    | '/api/public/mp-webhook'
    | '/api/public/wa-drain'
    | '/api/public/wa-webhook'
    | '/app/financeiro/categorias'
    | '/app/financeiro/cobrancas'
    | '/app/financeiro/despesas'
    | '/app/financeiro/inadimplencia'
    | '/app/financeiro/pagamentos'
    | '/app/financeiro/whatsapp'
    | '/auth/convite/$token'
    | '/app/financeiro'
    | '/api/public/hooks/lembretes-cobranca'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/app'
    | '/blog'
    | '/contato'
    | '/lgpd'
    | '/onboarding'
    | '/precos'
    | '/privacidade'
    | '/recursos'
    | '/sobre'
    | '/status'
    | '/termos'
    | '/app/condominio'
    | '/app/configuracoes'
    | '/app/documentos'
    | '/app/encomendas'
    | '/app/financeiro'
    | '/app/moradores'
    | '/app/ocorrencias'
    | '/app/preferencias-notificacao'
    | '/app/reservas'
    | '/app/visitantes'
    | '/app/whatsapp'
    | '/auth/cadastro'
    | '/auth/callback'
    | '/auth/esqueci-senha'
    | '/auth/login'
    | '/auth/redefinir-senha'
    | '/app/'
    | '/api/public/mp-webhook'
    | '/api/public/wa-drain'
    | '/api/public/wa-webhook'
    | '/app/financeiro/categorias'
    | '/app/financeiro/cobrancas'
    | '/app/financeiro/despesas'
    | '/app/financeiro/inadimplencia'
    | '/app/financeiro/pagamentos'
    | '/app/financeiro/whatsapp'
    | '/auth/convite/$token'
    | '/app/financeiro/'
    | '/api/public/hooks/lembretes-cobranca'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  AppRoute: typeof AppRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  LgpdRoute: typeof LgpdRoute
  OnboardingRoute: typeof OnboardingRoute
  PrecosRoute: typeof PrecosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecursosRoute: typeof RecursosRoute
  SobreRoute: typeof SobreRoute
  StatusRoute: typeof StatusRoute
  TermosRoute: typeof TermosRoute
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthEsqueciSenhaRoute: typeof AuthEsqueciSenhaRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRedefinirSenhaRoute: typeof AuthRedefinirSenhaRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
  ApiPublicWaDrainRoute: typeof ApiPublicWaDrainRoute
  ApiPublicWaWebhookRoute: typeof ApiPublicWaWebhookRoute
  AuthConviteTokenRoute: typeof AuthConviteTokenRoute
  ApiPublicHooksLembretesCobrancaRoute: typeof ApiPublicHooksLembretesCobrancaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/redefinir-senha': {
      id: '/auth/redefinir-senha'
      path: '/auth/redefinir-senha'
      fullPath: '/auth/redefinir-senha'
      preLoaderRoute: typeof AuthRedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/esqueci-senha': {
      id: '/auth/esqueci-senha'
      path: '/auth/esqueci-senha'
      fullPath: '/auth/esqueci-senha'
      preLoaderRoute: typeof AuthEsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cadastro': {
      id: '/auth/cadastro'
      path: '/auth/cadastro'
      fullPath: '/auth/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visitantes': {
      id: '/app/visitantes'
      path: '/visitantes'
      fullPath: '/app/visitantes'
      preLoaderRoute: typeof AppVisitantesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reservas': {
      id: '/app/reservas'
      path: '/reservas'
      fullPath: '/app/reservas'
      preLoaderRoute: typeof AppReservasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/preferencias-notificacao': {
      id: '/app/preferencias-notificacao'
      path: '/preferencias-notificacao'
      fullPath: '/app/preferencias-notificacao'
      preLoaderRoute: typeof AppPreferenciasNotificacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ocorrencias': {
      id: '/app/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/app/ocorrencias'
      preLoaderRoute: typeof AppOcorrenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/moradores': {
      id: '/app/moradores'
      path: '/moradores'
      fullPath: '/app/moradores'
      preLoaderRoute: typeof AppMoradoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/encomendas': {
      id: '/app/encomendas'
      path: '/encomendas'
      fullPath: '/app/encomendas'
      preLoaderRoute: typeof AppEncomendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/condominio': {
      id: '/app/condominio'
      path: '/condominio'
      fullPath: '/app/condominio'
      preLoaderRoute: typeof AppCondominioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro/': {
      id: '/app/financeiro/'
      path: '/'
      fullPath: '/app/financeiro/'
      preLoaderRoute: typeof AppFinanceiroIndexRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/auth/convite/$token': {
      id: '/auth/convite/$token'
      path: '/auth/convite/$token'
      fullPath: '/auth/convite/$token'
      preLoaderRoute: typeof AuthConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/financeiro/whatsapp': {
      id: '/app/financeiro/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/financeiro/whatsapp'
      preLoaderRoute: typeof AppFinanceiroWhatsappRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/financeiro/pagamentos': {
      id: '/app/financeiro/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/financeiro/pagamentos'
      preLoaderRoute: typeof AppFinanceiroPagamentosRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/financeiro/inadimplencia': {
      id: '/app/financeiro/inadimplencia'
      path: '/inadimplencia'
      fullPath: '/app/financeiro/inadimplencia'
      preLoaderRoute: typeof AppFinanceiroInadimplenciaRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/financeiro/despesas': {
      id: '/app/financeiro/despesas'
      path: '/despesas'
      fullPath: '/app/financeiro/despesas'
      preLoaderRoute: typeof AppFinanceiroDespesasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/financeiro/cobrancas': {
      id: '/app/financeiro/cobrancas'
      path: '/cobrancas'
      fullPath: '/app/financeiro/cobrancas'
      preLoaderRoute: typeof AppFinanceiroCobrancasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/financeiro/categorias': {
      id: '/app/financeiro/categorias'
      path: '/categorias'
      fullPath: '/app/financeiro/categorias'
      preLoaderRoute: typeof AppFinanceiroCategoriasRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/api/public/wa-webhook': {
      id: '/api/public/wa-webhook'
      path: '/api/public/wa-webhook'
      fullPath: '/api/public/wa-webhook'
      preLoaderRoute: typeof ApiPublicWaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wa-drain': {
      id: '/api/public/wa-drain'
      path: '/api/public/wa-drain'
      fullPath: '/api/public/wa-drain'
      preLoaderRoute: typeof ApiPublicWaDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lembretes-cobranca': {
      id: '/api/public/hooks/lembretes-cobranca'
      path: '/api/public/hooks/lembretes-cobranca'
      fullPath: '/api/public/hooks/lembretes-cobranca'
      preLoaderRoute: typeof ApiPublicHooksLembretesCobrancaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppFinanceiroRouteChildren {
  AppFinanceiroCategoriasRoute: typeof AppFinanceiroCategoriasRoute
  AppFinanceiroCobrancasRoute: typeof AppFinanceiroCobrancasRoute
  AppFinanceiroDespesasRoute: typeof AppFinanceiroDespesasRoute
  AppFinanceiroInadimplenciaRoute: typeof AppFinanceiroInadimplenciaRoute
  AppFinanceiroPagamentosRoute: typeof AppFinanceiroPagamentosRoute
  AppFinanceiroWhatsappRoute: typeof AppFinanceiroWhatsappRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
}

const AppFinanceiroRouteChildren: AppFinanceiroRouteChildren = {
  AppFinanceiroCategoriasRoute: AppFinanceiroCategoriasRoute,
  AppFinanceiroCobrancasRoute: AppFinanceiroCobrancasRoute,
  AppFinanceiroDespesasRoute: AppFinanceiroDespesasRoute,
  AppFinanceiroInadimplenciaRoute: AppFinanceiroInadimplenciaRoute,
  AppFinanceiroPagamentosRoute: AppFinanceiroPagamentosRoute,
  AppFinanceiroWhatsappRoute: AppFinanceiroWhatsappRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
}

const AppFinanceiroRouteWithChildren = AppFinanceiroRoute._addFileChildren(
  AppFinanceiroRouteChildren,
)

interface AppRouteChildren {
  AppCondominioRoute: typeof AppCondominioRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppEncomendasRoute: typeof AppEncomendasRoute
  AppFinanceiroRoute: typeof AppFinanceiroRouteWithChildren
  AppMoradoresRoute: typeof AppMoradoresRoute
  AppOcorrenciasRoute: typeof AppOcorrenciasRoute
  AppPreferenciasNotificacaoRoute: typeof AppPreferenciasNotificacaoRoute
  AppReservasRoute: typeof AppReservasRoute
  AppVisitantesRoute: typeof AppVisitantesRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCondominioRoute: AppCondominioRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppEncomendasRoute: AppEncomendasRoute,
  AppFinanceiroRoute: AppFinanceiroRouteWithChildren,
  AppMoradoresRoute: AppMoradoresRoute,
  AppOcorrenciasRoute: AppOcorrenciasRoute,
  AppPreferenciasNotificacaoRoute: AppPreferenciasNotificacaoRoute,
  AppReservasRoute: AppReservasRoute,
  AppVisitantesRoute: AppVisitantesRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  AppRoute: AppRouteWithChildren,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  LgpdRoute: LgpdRoute,
  OnboardingRoute: OnboardingRoute,
  PrecosRoute: PrecosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecursosRoute: RecursosRoute,
  SobreRoute: SobreRoute,
  StatusRoute: StatusRoute,
  TermosRoute: TermosRoute,
  AuthCadastroRoute: AuthCadastroRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthEsqueciSenhaRoute: AuthEsqueciSenhaRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRedefinirSenhaRoute: AuthRedefinirSenhaRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
  ApiPublicWaDrainRoute: ApiPublicWaDrainRoute,
  ApiPublicWaWebhookRoute: ApiPublicWaWebhookRoute,
  AuthConviteTokenRoute: AuthConviteTokenRoute,
  ApiPublicHooksLembretesCobrancaRoute: ApiPublicHooksLembretesCobrancaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
